title: Isurwars's Physics Logbook
email: isurwars@gmail.com
baseurl: ""
url: "https://isurwars.github.io/" # Reemplaza con tu URL
timezone: America/Mexico_City # Ajusta a tu zona horaria
permalink: /:title/
markdown: kramdown

# Configuración del Tema
# La sintaxis simple 'jekyll/minima' funciona mejor que especificar una versión.
remote_theme: jekyll/minima

# Configuración de Minima para el Modo Oscuro
minima:
  # Opciones para 'skin':
  # 1. 'auto': Cambia automáticamente según la configuración del sistema del usuario (RECOMENDADO)
  # 2. 'dark': Fuerza el tema oscuro
  # 3. 'light': Fuerza el tema claro
  skin: "dark"

# Plugins
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
